micronaut:
  application:
    name: bug-micronaut-validation

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        globally_quoted_identifiers: true

datasources:
  default:
    url: jdbc:h2:./db

